eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: client-a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    
server:
  port: 8762